import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    content: {
        paddingBottom: 100,
    },
    inner: {
        paddingHorizontal: 24,
        paddingTop: 54,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        marginBottom: 20,
    },
    backButton: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: '#f1f5f9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerText: {
        flex: 1,
    },
    sectionTitle: {
        fontFamily: 'Inter_700Bold',
        fontSize: 22,
        color: '#112332',
    },
    sectionSubtitle: {
        marginTop: 2,
        fontSize: 13,
        color: '#65717c',
    },
    avatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
    },
    memberList: {
        paddingVertical: 12,
        gap: 12,
        marginBottom: 16,
    },
    memberItem: {
        width: 72,
        alignItems: 'center',
        gap: 4,
    },
    addButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    memberName: {
        fontSize: 11,
        fontWeight: '600',
        color: '#4c5863',
        textAlign: 'center',
        width: '100%',
    },
    memberBalanceLabel: {
        fontSize: 10,
        color: '#9ca3af',
    },
    memberBalance: {
        fontSize: 10,
        fontWeight: '700',
    },
    balancePositive: {
        color: '#16a34a',
    },
    balanceNegative: {
        color: '#dc2626',
    },
    balanceZero: {
        color: '#6b7280',
    },
    balanceCard: {
        width: '100%',
        borderRadius: 28,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 4,
        marginBottom: 28,
    },
    label: {
        fontSize: 14,
        color: '#374151',
        fontWeight: '600',
    },
    value: {
        fontSize: 38,
        fontWeight: 'bold',
        color: '#111',
        marginTop: 6,
    },
    infoContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        borderRadius: 18,
        padding: 14,
    },
    infoBox: {
        flex: 1,
        alignItems: 'center',
    },
    divider: {
        width: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.1)',
        marginHorizontal: 10,
    },
    infoLabel: {
        fontSize: 12,
        color: '#4b5563',
        fontWeight: '600',
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '700',
        color: '#111827',
        marginTop: 4,
    },
    textPositive: {
        color: '#16a34a',
    },
    textNegative: {
        color: '#dc2626',
    },
    actions: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 24,
    },
    actionItem: {
        alignItems: 'center',
        gap: 6,
    },
    actionButton: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    actionButtonDisabled: {
        backgroundColor: '#f3f4f6',
        borderColor: '#e5e7eb',
    },
    actionText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#1f2937',
    },
    actionTextDisabled: {
        color: '#9ca3af',
    },
    expensesHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    expensesTitle: {
        fontFamily: 'Inter_700Bold',
        fontSize: 18,
        color: '#112332',
    },
    emptyExpenses: {
        paddingVertical: 24,
        alignItems: 'center',
    },
    emptyExpensesText: {
        color: '#9ca3af',
        fontSize: 14,
    },
    expenseList: {
        paddingBottom: 20,
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    modalBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    expenseModal: {
        width: '100%',
        maxHeight: '90%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 24,
        paddingTop: 12,
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -6 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 10,
    },
    paymentModal: {
        width: '100%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 24,
        paddingTop: 12,
        paddingBottom: 34,
        backgroundColor: '#fff',
    },
    historyModal: {
        width: '100%',
        height: '80%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 24,
        paddingTop: 12,
        backgroundColor: '#fff',
    },
    inviteModal: {
        width: '100%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 24,
        paddingTop: 12,
        paddingBottom: 34,
        backgroundColor: '#fff',
    },
    modalHandle: {
        alignSelf: 'center',
        width: 40,
        height: 5,
        borderRadius: 999,
        backgroundColor: '#e2e8f0',
        marginBottom: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 16,
        marginBottom: 22,
    },
    modalTitle: {
        fontFamily: 'Inter_700Bold',
        fontSize: 24,
        color: '#112332',
    },
    modalSubtitle: {
        marginTop: 4,
        fontSize: 13,
        color: '#65717c',
    },
    closeButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#f1f5f9',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalForm: {
        gap: 16,
        marginBottom: 24,
    },
    formGroup: {
        width: '100%',
    },
    modalLabel: {
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 8,
        color: '#112332',
    },
    modalInput: {
        borderWidth: 1,
        borderColor: '#cbd5e1',
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        color: '#111827',
        backgroundColor: '#f8fafc',
    },
    modalInputError: {
        borderColor: '#ef4444',
    },
    errorText: {
        color: '#ef4444',
        fontSize: 12,
        marginTop: 4,
    },
    payerList: {
        gap: 10,
        paddingVertical: 4,
    },
    payerItem: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 20,
        backgroundColor: '#f1f5f9',
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    payerItemSelected: {
        backgroundColor: '#2563eb',
        borderColor: '#2563eb',
    },
    payerText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#112332',
    },
    payerTextSelected: {
        color: '#fff',
    },
    receiptPickerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 14,
        borderWidth: 1,
        borderColor: '#cbd5e1',
        borderStyle: 'dashed',
        borderRadius: 12,
        backgroundColor: '#f8fafc',
        gap: 12,
    },
    receiptPickerIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#f1f5f9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    receiptPickerText: {
        flex: 1,
    },
    receiptPickerTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#112332',
    },
    receiptPickerHint: {
        fontSize: 12,
        color: '#65717c',
        marginTop: 2,
    },
    receiptPreviewCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        borderRadius: 12,
        backgroundColor: '#f8fafc',
        gap: 12,
    },
    receiptPreview: {
        width: 50,
        height: 50,
        borderRadius: 8,
    },
    receiptPreviewInfo: {
        flex: 1,
    },
    receiptPreviewTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#112332',
    },
    receiptPreviewName: {
        fontSize: 12,
        color: '#65717c',
        marginTop: 2,
    },
    removeReceiptButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#fde8e8',
        justifyContent: 'center',
        alignItems: 'center',
    },
    saveButton: {
        backgroundColor: '#112332',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 56,
        marginBottom: 20,
    },
    saveButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    paymentActions: {
        flexDirection: 'row',
        gap: 12,
    },
    payButton: {
        flex: 1,
        minHeight: 52,
        borderRadius: 26,
        backgroundColor: '#112332',
        alignItems: 'center',
        justifyContent: 'center',
    },
    payButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '800',
    },
    cancelButton: {
        flex: 1,
        minHeight: 52,
        borderRadius: 26,
        backgroundColor: '#e2e8f0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: {
        color: '#112332',
        fontSize: 15,
        fontWeight: '800',
    },
    historyList: {
        paddingBottom: 40,
    },
    inviteCodeCard: {
        backgroundColor: '#f8fafc',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        padding: 20,
        alignItems: 'center',
        marginBottom: 24,
    },
    inviteCodeLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#64748b',
        marginBottom: 8,
    },
    inviteCode: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1e293b',
        textAlign: 'center',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#cbd5e1',
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 16,
        width: '100%',
    },
    inviteCodeHint: {
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center',
        marginTop: 12,
        lineHeight: 18,
    },
    inviteActions: {
        flexDirection: 'row',
        gap: 12,
    },
    shareButton: {
        flex: 1,
        minHeight: 52,
        borderRadius: 26,
        backgroundColor: '#2563eb',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    shareButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '800',
    },
});
