import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        paddingHorizontal: 24,
        paddingTop: 54,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 22,
    },
    title: {
        fontFamily: 'Inter_700Bold',
        fontSize: 36,
        color: '#112332',
        flexDirection: 'row',
        alignItems: 'center',
    },
    subtitle: {
        maxWidth: 280,
        marginTop: 8,
        fontSize: 15,
        lineHeight: 22,
        color: '#5f6b76',
    },
    quickActionsContainer: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 24,
    },
    headerActionButton: {
        flex: 1,
        flexDirection: 'row',
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 14,
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#f1f5f9',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 2,
    },
    headerActionText: {
        flex: 1,
    },
    headerActionTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#112332',
    },
    headerActionSubtitle: {
        marginTop: 2,
        fontSize: 11,
        color: '#6b7280',
    },
    headerActionIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    list: {
        paddingBottom: 100,
    },
    footerActions: {
        gap: 16,
        marginTop: 24,
    },
    createCard: {
        minHeight: 120,
        borderRadius: 28,
        padding: 20,
        backgroundColor: '#112332',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    createCircle: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    createTextArea: {
        flex: 1,
    },
    createTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#fff',
    },
    createSubtitle: {
        marginTop: 4,
        fontSize: 13,
        lineHeight: 18,
        color: '#d7dee6',
    },
    joinCard: {
        minHeight: 110,
        borderRadius: 28,
        padding: 20,
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    joinCircle: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#F2F56B',
        alignItems: 'center',
        justifyContent: 'center',
    },
    joinTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#112332',
    },
    joinSubtitle: {
        marginTop: 4,
        fontSize: 13,
        lineHeight: 18,
        color: '#5f6b76',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: 60,
    },
    emptyJoinButton: {
        minHeight: 52,
        borderRadius: 26,
        paddingHorizontal: 24,
        backgroundColor: '#f1f5f9',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        marginTop: -10,
    },
    emptyJoinButtonText: {
        color: '#112332',
        fontSize: 14,
        fontWeight: '800',
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    modalBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.4)',
    },
    joinModal: {
        width: '100%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 24,
        paddingTop: 12,
        paddingBottom: 34,
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -6 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
    },
    modalHandle: {
        alignSelf: 'center',
        width: 40,
        height: 5,
        borderRadius: 999,
        backgroundColor: '#e2e8f0',
        marginBottom: 20,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 16,
        marginBottom: 22,
    },
    modalTitle: {
        fontFamily: 'Inter_700Bold',
        fontSize: 26,
        color: '#112332',
    },
    modalSubtitle: {
        marginTop: 4,
        fontSize: 13,
        color: '#65717c',
    },
    closeButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#f1f5f9',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalForm: {
        marginBottom: 24,
    },
    modalLabel: {
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 8,
        color: '#112332',
    },
    modalInput: {
        borderWidth: 1,
        borderColor: '#cbd5e1',
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        color: '#111827',
        backgroundColor: '#f8fafc',
    },
    modalActions: {
        flexDirection: 'row',
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        minHeight: 52,
        borderRadius: 26,
        backgroundColor: '#e2e8f0',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: {
        color: '#112332',
        fontSize: 15,
        fontWeight: '800',
    },
    enterButton: {
        flex: 1,
        minHeight: 52,
        borderRadius: 26,
        backgroundColor: '#112332',
        alignItems: 'center',
        justifyContent: 'center',
    },
    enterButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '800',
    },
});
