import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    content: {
        paddingHorizontal: 24,
        paddingTop: 54,
        paddingBottom: 100,
    },
    header: {
        alignItems: 'center',
        marginBottom: 24,
    },
    avatarWrapper: {
        width: 112,
        height: 112,
        borderRadius: 56,
        backgroundColor: '#f1f5f9',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 10,
        elevation: 5,
    },
    avatar: {
        width: 104,
        height: 104,
        borderRadius: 52,
    },
    name: {
        marginTop: 18,
        fontFamily: 'Inter_700Bold',
        fontSize: 30,
        color: '#112332',
        textAlign: 'center',
    },
    email: {
        marginTop: 6,
        fontSize: 15,
        color: '#65717c',
        textAlign: 'center',
    },
    editButton: {
        marginTop: 18,
        minHeight: 46,
        borderRadius: 23,
        paddingHorizontal: 18,
        backgroundColor: '#f1f5f9',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    editButtonText: {
        color: '#112332',
        fontSize: 15,
        fontWeight: '800',
    },
    statsRow: {
        flexDirection: 'row',
        gap: 14,
        marginBottom: 14,
    },
    statCard: {
        flex: 1,
        minHeight: 104,
        borderRadius: 24,
        padding: 18,
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#f1f5f9',
        justifyContent: 'center',
    },
    statValue: {
        fontSize: 26,
        fontWeight: '900',
        color: '#112332',
    },
    statLabel: {
        marginTop: 6,
        fontSize: 13,
        color: '#65717c',
        fontWeight: '700',
    },
    balanceCard: {
        minHeight: 110,
        borderRadius: 28,
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        marginBottom: 26,
    },
    balanceIcon: {
        width: 56,
        height: 56,
        borderRadius: 28,
        alignItems: 'center',
        justifyContent: 'center',
    },
    balanceText: {
        flex: 1,
    },
    balanceLabel: {
        fontSize: 13,
        fontWeight: '700',
    },
    balanceValue: {
        marginTop: 4,
        fontSize: 28,
        fontWeight: '900',
    },
    section: {
        gap: 12,
    },
    sectionTitle: {
        fontFamily: 'Inter_700Bold',
        fontSize: 22,
        color: '#112332',
        marginBottom: 4,
    },
    optionCard: {
        minHeight: 78,
        borderRadius: 20,
        padding: 14,
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#f1f5f9',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    optionIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.02,
        shadowRadius: 2,
        elevation: 1,
    },
    optionText: {
        flex: 1,
    },
    optionTitle: {
        fontSize: 15,
        fontWeight: '800',
        color: '#112332',
    },
    optionSubtitle: {
        marginTop: 3,
        fontSize: 12,
        lineHeight: 17,
        color: '#65717c',
    },
    logoutButton: {
        minHeight: 58,
        borderRadius: 29,
        backgroundColor: '#112332',
        marginTop: 28,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    logoutText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '800',
    },
    // Modals Styles
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
        width: '90%',
        maxWidth: 400,
        backgroundColor: '#fff',
        borderRadius: 24,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 24,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontFamily: 'Inter_700Bold',
        fontSize: 22,
        color: '#112332',
    },
    label: {
        fontSize: 14,
        fontWeight: '700',
        color: '#112332',
        marginBottom: 8,
    },
    formGroup: {
        marginBottom: 16,
    },
    input: {
        borderWidth: 1,
        borderColor: '#e2e8f0',
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        color: '#1e293b',
        backgroundColor: '#f8fafc',
    },
    inputDisabled: {
        backgroundColor: '#e2e8f0',
        color: '#64748b',
        borderColor: '#cbd5e1',
    },
    helpText: {
        marginTop: 6,
        fontSize: 12,
        color: '#64748b',
        lineHeight: 18,
    },
    saveButton: {
        backgroundColor: '#112332',
        padding: 16,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 52,
        marginTop: 8,
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    switchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    switchTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#112332',
    },
    switchSubtitle: {
        fontSize: 12,
        color: '#64748b',
    },
});
